### ISSUE TITLE
[bug] : syntax error occured, trying to view in vscode

### ISSUE THREAD

**Issue by lonebots** [kiwicampus/ros2_graph#14]
## Steps to reproduce the error
1. generated the `turtle_diagram.md` file using 
```bash
ros2_graph /turtlesim -o turtle_diagram.md
```

2. tried to view the mark down file in vscode via [Markdown All in One](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one) extension and the following error popped up, it shows syntax error

![image](https://user-images.githubusercontent.com/46082779/214228636-4b0eb4c5-8314-438b-96f7-fa138a95313f.png)

**Comment by garzonwilmer5** [comment]
Hi, as I can see, we use the same extension [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid), please verify its version.

**Comment by lonebots** [comment]
> [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid), please verify its version.

I have `version 1.17.4`  of the above mentioned extension installed and still I am getting the same issue.
<br>

![image](https://user-images.githubusercontent.com/46082779/214561777-2fd8bb25-ee48-4e06-a4a0-a083813321c3.png)

**Comment by BriceRenaudeau** [comment]
@lonebots 
I use the same extension and it works perfectly.

**Comment by BriceRenaudeau** [comment]
The only issue I got is when I what to manually change the graph (name or delete "clock") I have the following error:
`Cannot set properties of undefined (setting 'style')`

It's due to the last line:
 `linkStyle 23,24 fill:none,stroke:green;`
 That change the color of the arrows for actions and specify the links by number.
 
Hence removing link makes it break.

I removed the line because I don't use action for now. And I was able to remove nodes.

**Comment by charlielito** [comment]
> The only issue I got is when I what to manually change the graph (name or delete "clock") I have the following error: `Cannot set properties of undefined (setting 'style')`
> 
> It's due to the last line: `linkStyle 23,24 fill:none,stroke:green;` That change the color of the arrows for actions and specify the links by number.
> 
> Hence removing link makes it break.
> 
> I removed the line because I don't use action for now. And I was able to remove nodes.

@BriceRenaudeau would it be a nice feature to be able to exclude services/actions/topics from the graph by a flag?

**Comment by BriceRenaudeau** [comment]
It would be a good feature to have some flags (--actions --services --keys).
But in my opinion, this is not a priority as we can remove it manually from the text.

I would prefer a more readable file (comments, clean declarations, separated links) for easy adjustments.
In my case the "clock" topic is useless but some people may keep it.

You may even use a .yaml file to allow user-defined links ("===", "---" or "...")

**Comment by lonebots** [comment]
> I use the same extension and it works perfectly.

Hi, I don't understand what's happening here, for the error still prevails and I am not able to get the graphs on vscode. but the code generated by `ros2_graph` works flawlessly in the GitHub markdown preview.

**Comment by garzonwilmer5** [comment]
> > I use the same extension and it works perfectly.
> 
> Hi, I don't understand what's happening here, for me the error still prevails and I am not able to get the graphs on vscode. but the code generated by `ros2_graph` works flawlessly in the GitHub markdown preview.

There is something that worries me in your case, the error says that you are using Mermaid version 8.8.3 but the latest version of the vs code extension supports Mermaid version 9.3.0. Have you made any changes to the extension settings?

**Comment by lonebots** [comment]
>  you made any changes to the extension settings?

No, I haven't made any changes to extension settings, anyways I will have a check on that once more.

**Comment by BriceRenaudeau** [comment]
New info.
It was working perfectly but now it doesn't. (same code) 
- mermaid version 9.3.0
- Cannot set properties of undefined (setting 'style')

There is an issue with the **linkStyle** having number out of range.
it happens when there is actions .

**Comment by BriceRenaudeau** [comment]
it's a wrong addition in the link count.
https://github.com/kiwicampus/ros2_graph/blob/b4c8d5bf3f1998e9036c632d4c5bce2f3d808523/ros2_graph/graph_generator.py#L433

must be `links_count += links_count_aserver`

adding action links and not service links

**Comment by BriceRenaudeau** [comment]
Do you want me to do a PR for this?

**Comment by garzonwilmer5** [comment]
You are right there is an error, please make the PR.
